# Pyladies Paraíba - Quem Somos

*Descrição feita no dia 26 de abril de 2020*

In [1]:
import pandas as pd
import unidecode

Comando para que o dataframe seja exibido sem truncar a informação.

In [2]:
pd.set_option('display.max_colwidth', None)

Lendo os dados do formulário de participação. Os dados aqui analisados são anonimizados para preservar a privacidade das ladies.

In [3]:
ladies = pd.read_csv("../dados/quem_somos.tsv", sep='\t')
ladies.head()

,Carimbo de data/hora,Conta pra gente o que mais te interessa,Cidade atual,Qual a sua área de formação?
0,05/07/2019 22:44:52,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Tecnologia
1,02/07/2019 15:52:41,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",João Pessoa,Tecnologia
2,23/07/2019 14:05:19,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",Campina Grande,Tecnologia
3,09/07/2019 23:06:44,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Comunicação em Mídias Digitais
4,23/07/2019 16:32:51,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Comunicação em Mídias Digitais

### Total de ladies

In [4]:
len(ladies)

76

Vendo os tipos de dados de cada coluna.

In [5]:
ladies.dtypes

Carimbo de data/hora                       object
Conta pra gente o que mais te interessa    object
Cidade atual                               object
Qual a sua área de formação?               object
dtype: object

Para que possamos entender melhor sobre quando as ladies entraram precisamos transformar o campo *'Carimbo de data/hora'* em data ao invés de texto. Apenas assim poderemos pegar o mês e o ano de forma automática.

In [6]:
ladies['preenchimento'] = pd.to_datetime(ladies["Carimbo de data/hora"], dayfirst=True)
ladies.head()

,Carimbo de data/hora,Conta pra gente o que mais te interessa,Cidade atual,Qual a sua área de formação?,preenchimento
0,05/07/2019 22:44:52,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Tecnologia,2019-07-05 22:44:52
1,02/07/2019 15:52:41,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",João Pessoa,Tecnologia,2019-07-02 15:52:41
2,23/07/2019 14:05:19,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",Campina Grande,Tecnologia,2019-07-23 14:05:19
3,09/07/2019 23:06:44,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Comunicação em Mídias Digitais,2019-07-09 23:06:44
4,23/07/2019 16:32:51,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Comunicação em Mídias Digitais,2019-07-23 16:32:51

In [7]:
ladies['mes de preenchimento'] = ladies['preenchimento'].dt.month_name(locale='pt_BR.UTF-8')
ladies.astype({'mes de preenchimento': 'category'}).dtypes
    
ladies['ano de preenchimento'] = ladies['preenchimento'].dt.year
ladies.astype({'ano de preenchimento': 'category'}).dtypes

ladies['numero mes de preenchimento'] = ladies['preenchimento'].dt.month
ladies.astype({'numero mes de preenchimento': 'category'}).dtypes

ladies.head()

,Carimbo de data/hora,Conta pra gente o que mais te interessa,Cidade atual,Qual a sua área de formação?,preenchimento,mes de preenchimento,ano de preenchimento,numero mes de preenchimento
0,05/07/2019 22:44:52,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Tecnologia,2019-07-05 22:44:52,Julho,2019,7
1,02/07/2019 15:52:41,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",João Pessoa,Tecnologia,2019-07-02 15:52:41,Julho,2019,7
2,23/07/2019 14:05:19,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",Campina Grande,Tecnologia,2019-07-23 14:05:19,Julho,2019,7
3,09/07/2019 23:06:44,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Comunicação em Mídias Digitais,2019-07-09 23:06:44,Julho,2019,7
4,23/07/2019 16:32:51,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",João Pessoa,Comunicação em Mídias Digitais,2019-07-23 16:32:51,Julho,2019,7

### Quando entramos?

In [8]:
ladies.groupby(['ano de preenchimento', 'mes de preenchimento', 'numero mes de preenchimento']).size().reset_index(name='quantidade').sort_values(['ano de preenchimento', 'numero mes de preenchimento'])

,ano de preenchimento,mes de preenchimento,numero mes de preenchimento,quantidade
2,2019,Julho,7,37
0,2019,Agosto,8,5
5,2019,Setembro,9,5
4,2019,Outubro,10,6
3,2019,Novembro,11,3
1,2019,Dezembro,12,3
7,2020,Março,3,13
6,2020,Abril,4,4

O nosso grupo começou em setembro de 2018 mas os formulários para registrar os dados das ladies que entravam só começou a ser disponibilizado em 2019, quando organizamos o processo de entrada e vinculamos ele ao preenchimento desse form. O objetivo do form era alem de ter os dados para contato das pessoas interessadas registrar qual era a sua principal demanda.

Então podemos dizer que parte dessas entradas que são relatadas como julho de 2019 pode ter acontecido a partir de setembro de 2018.

### Onde Estamos?

In [9]:
ladies.groupby(['Cidade atual']).size().reset_index(name='quantidade').sort_values('quantidade')

             Cidade atual  quantidade
0             João Pessoa           1
23           Santa Luzia            1
22           Rio Tinto-PB           1
21             Rio Tinto            1
20              Rio Tinto           1
19               Patos-PB           1
17                Paraíba           1
16               Monteiro           1
15            João pessoa           1
14        João Pessoa -PB           1
13       João Pessoa - PB           1
24               Solânea            1
25            joao pessoa           1
10           Joao pessoa            1
9             JOÃO PESSOA           1
8             JOAO PESSOA           1
4   Cachoeira dos Índios            1
1                Aroeiras           1
5              Cajazeiras           2
3                Cabedelo           2
2          CAMPINA GRANDE           2
12           João Pessoa            2
7         Campina Grande            3
18                  Patos           3
6          Campina Grande          17
11            João Pessoa          27

<img src="https://i.makeagif.com/media/4-26-2017/64PHj8.gif" align="left">

### Campo aberto pode dar uma dor de cabeça, né? 
#### Casa pessoa pode responder de uma forma. Prepare-se para isso.

In [10]:
ladies['Cidade atual'].str.lower().str.rstrip().str.lstrip().str.rstrip("-pb").str.rstrip("- pb")

0        joão pessoa
1        joão pessoa
2     campina grande
3        joão pessoa
4        joão pessoa
           ...
71       joão pessoa
72         rio tinto
73       joão pessoa
74       joão pessoa
75    campina grande
Name: Cidade atual, Length: 76, dtype: object

Aqui colocamos todas as respostas em letra minúscula, retiramos espaços em braco antes ou depois do texto que queremos assim como o sufixo '-pb'

In [11]:
ladies['Cidade atual'] = ladies['Cidade atual'].str.lower().str.rstrip().str.lstrip().str.rstrip("-pb").str.rstrip("- pb")
ladies.head()

,Carimbo de data/hora,Conta pra gente o que mais te interessa,Cidade atual,Qual a sua área de formação?,preenchimento,mes de preenchimento,ano de preenchimento,numero mes de preenchimento
0,05/07/2019 22:44:52,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.",joão pessoa,Tecnologia,2019-07-05 22:44:52,Julho,2019,7
1,02/07/2019 15:52:41,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",joão pessoa,Tecnologia,2019-07-02 15:52:41,Julho,2019,7
2,23/07/2019 14:05:19,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",campina grande,Tecnologia,2019-07-23 14:05:19,Julho,2019,7
3,09/07/2019 23:06:44,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",joão pessoa,Comunicação em Mídias Digitais,2019-07-09 23:06:44,Julho,2019,7
4,23/07/2019 16:32:51,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",joão pessoa,Comunicação em Mídias Digitais,2019-07-23 16:32:51,Julho,2019,7

Aqui retiramos os acentos

In [12]:
ladies['Cidade atual'] = ladies['Cidade atual'].apply(unidecode.unidecode)

In [13]:
ladies.groupby(['Cidade atual']).size().reset_index(name='quantidade').sort_values('quantidade')

            Cidade atual  quantidade
0               aroeiras           1
2   cachoeira dos indios           1
6               monteiro           1
7                paraiba           1
10           santa luzia           1
11               solanea           1
1               cabedelo           2
3             cajazeiras           2
9              rio tinto           3
8                  patos           4
4         campina grande          22
5            joao pessoa          37

### Qual a nossa área?

In [14]:
ladies.groupby(['Qual a sua área de formação?']).size().reset_index(name='quantidade').sort_values('quantidade')

                                Qual a sua área de formação?  quantidade
0                                              Administração           1
1                                                   Biologia           1
3  Comunicação em Mídias Digitais (comunicação + tecnologia)           1
5                                                     Design           1
6                                         Saude/ cursando ti           1
9                                         Tecnologia e saúde           1
2                             Comunicação em Mídias Digitais           2
7                                                      Saúde           3
4                                     Comunicação/Jornalismo           4
8                                                 Tecnologia          61

### O que queremos?

In [15]:
ladies.groupby(['Conta pra gente o que mais te interessa']).size().reset_index(name='quantidade').sort_values('quantidade')

,Conta pra gente o que mais te interessa,quantidade
8,"Aprender Python do zero.., Quero saber como utilizar Python pra desenvolvimento WEB.., Outras linguagens de programação [Java e JavaScript], ficar por dentro das atividades de outras colegas da área na região, networking",1
14,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente..",1
11,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Ainda tenho muito em que melhorar, sei o básico e quem sabe quando eu melhorar ajudar outras pessoas o/",1
19,"Quero saber como utilizar Python pra desenvolvimento WEB.., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente..",1
18,"Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",1
16,Python para GIS,1
17,Quero saber como utilizar Python pra desenvolvimento WEB.,1
5,"Aprender Python do zero.., Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.",1
2,"Aprender Python do zero., Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",1
1,"Aprender Python do zero., Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.",1
6,"Aprender Python do zero.., Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente..",1
7,"Aprender Python do zero.., Quero saber como utilizar Python pra desenvolvimento WEB..",2
13,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB..",2
20,Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.,3
4,Aprender Python do zero..,4
3,"Aprender Python do zero., Quero saber como utilizar Python pra desenvolvimento WEB.",4
12,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",5
15,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.",5
0,Aprender Python do zero.,9
9,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.,15
10,"Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas., Quero saber como utilizar Python pra desenvolvimento WEB.",16

Agrupar essa coluna requer um pouco mais de atenção pois aí nos temos um campo multivalorado.
A lady pode ter respondido tanto **'Aprender Python do zero'** quanto **'Aprender Python do zero, Aprender Python WEB'**.

Para entender melhor precisamos "explodir a coluna". 

O artigo [Pandas: Splitting (Exploding) a column into multiple rows do Suresh Sarda](https://medium.com/@sureshssarda/pandas-splitting-exploding-a-column-into-multiple-rows-b1b1d59ea12e) explica em detalhes a solução que vamos usar a seguir.

In [27]:
new_ladies = pd.DataFrame(ladies['Conta pra gente o que mais te interessa'].str.split(',').tolist(), 
                          index=ladies['preenchimento']).stack()
new_ladies.head()

preenchimento
2019-07-05 22:44:52  0             Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
                     1                                 Quero saber como utilizar Python pra desenvolvimento WEB.
2019-07-02 15:52:41  0             Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
                     1     Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.
2019-07-23 14:05:19  0             Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
dtype: object

In [28]:
new_ladies = new_ladies.reset_index([0, 'preenchimento'])
new_ladies.head()

,preenchimento,0
0,2019-07-05 22:44:52,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
1,2019-07-05 22:44:52,Quero saber como utilizar Python pra desenvolvimento WEB.
2,2019-07-02 15:52:41,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
3,2019-07-02 15:52:41,Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.
4,2019-07-23 14:05:19,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.

In [29]:
new_ladies.columns = ['preenchimento', 'interesse']
new_ladies.head()

,preenchimento,interesse
0,2019-07-05 22:44:52,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
1,2019-07-05 22:44:52,Quero saber como utilizar Python pra desenvolvimento WEB.
2,2019-07-02 15:52:41,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.
3,2019-07-02 15:52:41,Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente.
4,2019-07-23 14:05:19,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas.

### E agora vamos conseguimos descobrir nossos principais interesses o/

Uma mudança nas opções de resposta do form resultou numa despadronização para essa pergunta.
Algumas frases ficaram com pontos a mais no final e espaços em branco, por isso vamos retirá-los a seguir.

In [30]:
new_ladies['interesse'] = new_ladies['interesse'].str.rstrip(".").str.rstrip().str.lstrip()

In [31]:
new_ladies.groupby('interesse').size().reset_index(name='quantidade').sort_values('quantidade', ascending=False)

,interesse,quantidade
2,Já conheço o básico de Python. Agora quero conhecer aplicações mais práticas,49
5,Quero saber como utilizar Python pra desenvolvimento WEB,37
1,Aprender Python do zero,24
6,Tenho alguma experiência em Python e muita vontade de passar conhecimento pra frente,18
0,Ainda tenho muito em que melhorar,1
3,Outras linguagens de programação [Java e JavaScript],1
4,Python para GIS,1
7,ficar por dentro das atividades de outras colegas da área na região,1
8,networking,1
9,sei o básico e quem sabe quando eu melhorar ajudar outras pessoas o/,1